server:
  port: 8787
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true